name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  PACKAGE_NAME: chatboto

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x86_64
            artifact_name: chatboto-linux-x86_64
            asset_name: chatboto-linux-x86_64.tar.gz
            
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: linux-aarch64
            artifact_name: chatboto-linux-aarch64
            asset_name: chatboto-linux-aarch64.tar.gz
            
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: windows-x86_64
            artifact_name: chatboto-windows-x86_64
            asset_name: chatboto-windows-x86_64.zip
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
        
    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev

    - name: Install Cross-compilation Tools (aarch64)
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        
    - name: Install Cargo Deb
      if: runner.os == 'Linux' && matrix.target == 'x86_64-unknown-linux-gnu'
      run: cargo install cargo-deb
        
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
      env:
        CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
        
    - name: Package Windows Binaries
      if: matrix.os == 'windows-latest'
      run: |
        mkdir -p ${{ matrix.artifact_name }}
        cp target/${{ matrix.target }}/release/${{ env.PACKAGE_NAME }}.exe ${{ matrix.artifact_name }}/
        7z a ${{ matrix.asset_name }} ${{ matrix.artifact_name }}
        
    - name: Package Linux Binaries
      if: runner.os == 'Linux'
      run: |
        mkdir -p ${{ matrix.artifact_name }}/usr/bin
        cp target/${{ matrix.target }}/release/${{ env.PACKAGE_NAME }} ${{ matrix.artifact_name }}/usr/bin/
        chmod +x ${{ matrix.artifact_name }}/usr/bin/${{ env.PACKAGE_NAME }}
        tar -czvf ${{ matrix.asset_name }} ${{ matrix.artifact_name }}
        
    - name: Create DEB Package
      if: runner.os == 'Linux' && matrix.target == 'x86_64-unknown-linux-gnu'
      run: |
        cargo deb --target ${{ matrix.target }}
        cp target/${{ matrix.target }}/debian/*.deb chatboto-amd64.deb
        
    - name: Create RPM Package (Fedora)
      if: runner.os == 'Linux' && matrix.target == 'x86_64-unknown-linux-gnu'
      run: |
        sudo apt-get install -y rpm
        mkdir -p rpmbuild/{SPECS,SOURCES,BUILD,RPMS,SRPMS}
        
        # Create spec file
        cat > rpmbuild/SPECS/chatboto.spec << 'EOF'
        Name:           chatboto
        Version:        0.2.0
        Release:        1%{?dist}
        Summary:        ChatBoto AI chat application
        
        License:        MIT
        
        %description
        ChatBoto is an AI chat application supporting multiple LLM providers
        
        %install
        mkdir -p %{buildroot}/usr/bin
        cp %{_sourcedir}/chatboto %{buildroot}/usr/bin/
        chmod +x %{buildroot}/usr/bin/chatboto
        
        %files
        /usr/bin/chatboto
        
        %changelog
        * $(date '+%a %b %d %Y') GitHub Actions <actions@github.com> - 0.2.0-1
        - Automated RPM build
        EOF
        
        # Copy binary to SOURCES
        cp target/${{ matrix.target }}/release/${{ env.PACKAGE_NAME }} rpmbuild/SOURCES/
        
        # Build RPM
        rpmbuild --define "_topdir $(pwd)/rpmbuild" -ba rpmbuild/SPECS/chatboto.spec
        
        # Copy RPM to current directory
        cp rpmbuild/RPMS/x86_64/chatboto-*.rpm chatboto-fedora-x86_64.rpm
        
    - name: Create Arch Linux Package
      if: runner.os == 'Linux' && matrix.target == 'x86_64-unknown-linux-gnu'
      run: |
        mkdir -p arch-pkg/usr/bin
        cp target/${{ matrix.target }}/release/${{ env.PACKAGE_NAME }} arch-pkg/usr/bin/
        chmod +x arch-pkg/usr/bin/${{ env.PACKAGE_NAME }}
        tar -czvf chatboto-arch-x86_64.tar.gz -C arch-pkg .
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          ${{ matrix.asset_name }}
          chatboto-*.deb
          chatboto-*.rpm
          chatboto-arch-*.tar.gz

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        
      - name: List files
        run: find . -type f -name "chatboto-*" | sort
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: |
            **/chatboto-*.tar.gz
            **/chatboto-*.zip
            **/chatboto-*.deb
            **/chatboto-*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
